export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_SIGNUP_START = 'AUTH_SIGNUP_START'; // sprawdzone
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS'; // 
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';

export const AUTH_SIGNIN_START = 'AUTH_SIGNIN_START';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAIL = 'AUTH_SIGNIN_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_STATUS_RESET = 'AUTH_STATUS_RESET';

export const AUTH_SET_AUTH_REDIRECT_PATH = 'AUTH_SET_AUTH_REDIRECT_PATH';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';